#ifndef _INC_CERTCA
#define _INC_CERTCA

typedef enum  {
  ENUM_PERIOD_INVALID   = -1,
  ENUM_PERIOD_SECONDS   = 0,
  ENUM_PERIOD_MINUTES,
  ENUM_PERIOD_HOURS,
  ENUM_PERIOD_DAYS,
  ENUM_PERIOD_WEEKS,
  ENUM_PERIOD_MONTHS,
  ENUM_PERIOD_YEARS 
} ENUM_PERIOD;

#endif /*_INC_CERTCA*/
